---
image: "CentOS 7"
flavor: m1.small
networks:
  - public5
  - nodes-net
dns_network: nodes-net
security_groups:
  - secgroup_all_hosts
  - secgroup_allow_ssh
  - secgroup_lb_hosts
  - secgroup_node_hosts
