---
image: "CentOS 7"
flavor: webnode
networks:
  - public5
  - masters-net
  - etcds-net
  - nodes-net
dns_network: nodes-net
security_groups:
  - secgroup_all_hosts
  - secgroup_allow_ssh
  - secgroup_master_hosts
volumes:
  - name_suffix: "docker"
    size: 40
    type: iscsi
