---
- name: Populate ansible hostvars
  hosts: all
  gather_facts: false
  tasks: []

- name: Set up all VMs
  hosts: localhost
  tasks:
     - name: Set up Networks
       include_tasks: "tasks/task_setup_networks.yml"
     - name: Set up Security Groups
       include_tasks: "tasks/task_setup_security_groups.yml"
     - name: Set up VM
       include_tasks: "tasks/task_setup_vm.yml"
       vars:
         hostname: "{{ item }}"
         host: "{{ hostvars[item] }}"
       with_items:
         - "{{ groups['all'] }}"

- name: Configure VMs
  hosts: all
  gather_facts: true
  remote_user: centos
  become: true
  become_user: root
  tasks:
    - name: Activate all interfaces
      template:
        src: templates/ifcfg.j2
        dest: '/etc/sysconfig/network-scripts/ifcfg-{{ item }}'
        mode: 0644
        owner: root
        group: root
        force: false
      when: hostvars[inventory_hostname]["ansible_"+item]["type"] == "ether"
      with_items:
        - '{{ hostvars[inventory_hostname]["ansible_interfaces"] }}'
      notify:
         - restart network
    - name: Make sure network changes are activated now
      meta: flush_handlers

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
      listen: 'restart network'


# XXX TODO:
#  - activate all interfaces in all VMs
#    (right now they don't even do DHCP, thus they are unusable)
#  - set sensible security groups
#
