---
# To be used with the "nodes_by_name" inventory file!

- name: Populate ansible hostvars
  hosts: all
  gather_facts: false
  tags:
    - always
  tasks: []

- name: Configure Docker
  hosts: master_hosts,node_hosts,infra_hosts
  gather_facts: true
  remote_user: centos
  become: true
  become_user: root
  tags:
    - configure_docker
  tasks:
    - name: Install NetworkManager
      yum:
        name: NetworkManager
        state: present
    - name: Activate NetworkManager
      service:
        name: NetworkManager
        state: started
        enabled: true
    - name: Install OpenShift Repo
      yum:
        name: centos-release-openshift-origin
        state: present
    - name: Install package
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - centos-release-openshift-origin
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - origin-clients
    - name: Install Docker
      yum:
        name: docker-1.12.6
        state: present
    - name: Tweak storage config file
      template:
        src: docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644
    - name: Query for docker lv
      shell: 'lvs | grep docker-pool'
      changed_when: false
      register: lv_detect
      failed_when: lv_detect.rc != 0 and lv_detect.rc != 1
    - block:
        - name: Stop Docker
          service:
            name: docker
            state: stopped
        # note: can't delete/recreate the directory because we'd
        # loose the SELinux context and extended attribute.
        # Sadly, "state=empty" has not been invented, yet for file:.
        - name: Empty docker storage
          shell: 'rm -rf /var/lib/docker/*'
        - name: Reconfigure docker storage
          command: /bin/docker-storage-setup
      when: lv_detect.rc != 0
    - name: Activate Docker
      service:
        name: docker
        state: started
        enabled: true
