---
- name: get VM infos
  os_server_facts:
    cloud: '{{ cloud }}'
    endpoint_type: '{{ endpoint_type }}'
  delegate_to: localhost
  when: openstack_servers is not defined
- name: add temporary DNS resolver
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    state: present
    insertafter: '^search'
    regexp: '^nameserver 8.8.8.8$'
  become: true
  become_user: root
- name: Prepare DNS server list
  set_fact:
    os_dns_servers: '{{ os_dns_servers|default([]) + [ openstack_servers|selectattr("name", "equalto", item)|map(attribute="addresses")|map(attribute=dns_network)|first|map(attribute="addr")|first ] }}'
  with_items: '{{ groups.dns_hosts }}'
- name: Setup dnsmasq
  include_role:
    name:  dnsmasq
  vars:
    dnsmasq_resolvconf: true
    dnsmasq_host_domain: '{{ dns_default_domain }}'
    dnsmasq_host_search: '{{ dns_default_search }}'
    dnsmasq_host_resolvers: [ "127.0.0.1" ]
    dnsmasq_dhcp: false
    dnsmasq_tftp: false
    dnsmasq_conf_log: DAEMON
    dnsmasq_conf_listen: [ 127.0.0.1 ]
    dnsmasq_conf_bogus_priv: false
    dnsmasq_conf_no_hosts: true
    dnsmasq_conf_all_servers: true
    dnsmasq_conf_resolv:
    dnsmasq_conf_no_poll: true
    dnsmasq_conf_servers: '{{ os_dns_servers }}'
  become: true
  become_user: root
- name: Ignore DHCP-reported nameservers
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: 'supersede domain-name-servers 127.0.0.1;'
    state: present
    regexp: '^supersede domain-name-servers '
  become: true
  become_user: root
- name: Ignore DHCP-reported domain search settings
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: 'supersede domain-search "{{ dns_default_search }}";'
    state: present
    regexp: '^supersede domain-search '
  become: true
  become_user: root
- name: Ignore DHCP-reported domain name
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: 'supersede domain-name "{{ dns_default_domain }}";'
    state: present
    regexp: '^supersede domain-name '
  become: true
  become_user: root
