---
- set_fact:
    userdata: ""
- set_fact:
    userdata: "{{ lookup('template','templates/'+host.userdata_template) }}"
  when: host.userdata_template is defined
# Ensure the VM has the correct state in the OpenStack cloud.
- name: Set up VM
  os_server:
    cloud: '{{ cloud }}'
    endpoint_type: '{{ endpoint_type }}'
    image: '{{ host.image }}'
    name: '{{ hostname }}'
    key_name: '{{ key_name }}'
    availability_zone: '{{ host.availability_zone }}'
    flavor: '{{ host.flavor }}'
    state: present
    nics: 'net-name={{ host.networks|join(",net-name=") }}'
    security_groups: '{{ host.security_groups }}'
    userdata: '{{ userdata|default(omit) }}'
  register: my_vm
