---
- name: configure DNS zone files
  include_tasks: tasks/task_setup_dns_servers.yml
# we need a temporary DNS resolve so we can install packages with yum
- name: add temporary DNS resolver
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    state: present
    insertafter: '^search'
    regexp: '^nameserver 8.8.8.8$'
  become: true
  become_user: root
- name: Prepare secondary DNS server list
  set_fact:
    os_dns_servers: '{{ os_dns_servers|default([]) + [ openstack_servers|selectattr("name", "equalto", item)|map(attribute="addresses")|map(attribute="nodes-net")|first|map(attribute="addr")|first ] }}'
  with_items: '{{ groups.dns_hosts }}'
- name: configure DNS daemon
  include_role:
    name: tinx.bind
  vars:
    remote_zone_file_dir: /tmp/primary_zones
    allow_query: '{{ openshift_networks["nodes-net"].subnets|map(attribute="cidr")|list }}'
    allow_transfer: '{{ openshift_networks["nodes-net"].subnets|map(attribute="cidr")|list }}'
    also_notify: '{{ os_dns_servers }}'
    listen_on:
      - port: 53
        interfaces: '{{ openstack_servers|selectattr("name", "equalto", groups.dns_hidden_primary_hosts|first)|map(attribute="addresses")|map(attribute="nodes-net")|first|map(attribute="addr")|list }}'
    listen_on_v6: []
