---
- name: Ensure presence of network
  os_network:
    cloud: '{{ cloud }}'
    endpoint_type: '{{ endpoint_type }}'
    name: '{{ item.key }}'
    external: '{{ item.value.external }}'
    shared: '{{ item.value.shared }}'
    state: present
  with_dict: '{{ hostvars[inventory_hostname].openshift_networks }}'
- name: Ensure presense of subnets
  include_tasks: "tasks/tasks_setup_subnets.yml"
  vars:
    os_network: '{{ item.key }}'
    os_subnets: '{{ item.value.subnets }}'
  with_dict: '{{ hostvars[inventory_hostname].openshift_networks }}'
